[package]
name = "mdbook_indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.12", features = ["cargo", "wrap_help"] }
mdbook = "0.4.43"
pulldown-cmark = "0.12"
serde_json = "1.0.133"
semver = "1.0.17"

[dev-dependencies]
